name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - master
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FPV_MAP_20AAA }}'
          projectId: fpv-map-20aaa
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
